# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PM_gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import warnings
warnings.filterwarnings("ignore")

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(975, 600)
        MainWindow.setMaximumSize(QtCore.QSize(975, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("source/511.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 941, 351))
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_3.setGeometry(QtCore.QRect(540, 10, 81, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_3.setGeometry(QtCore.QRect(630, 10, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_2.setGeometry(QtCore.QRect(270, 10, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(10, 150, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.comboBox_4 = QtWidgets.QComboBox(self.tab)
        self.comboBox_4.setGeometry(QtCore.QRect(420, 100, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(290, 100, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(380, 50, 331, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_9.setGeometry(QtCore.QRect(710, 50, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_4.setGeometry(QtCore.QRect(320, 50, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(10, 50, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_5.setGeometry(QtCore.QRect(240, 150, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_5.setDragEnabled(False)
        self.lineEdit_5.setReadOnly(False)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(840, 230, 81, 41))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_8.setGeometry(QtCore.QRect(520, 150, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_8.setDragEnabled(False)
        self.lineEdit_8.setReadOnly(False)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(650, 150, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(840, 280, 81, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_7.setGeometry(QtCore.QRect(830, 150, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_7.setDragEnabled(False)
        self.lineEdit_7.setReadOnly(False)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(360, 150, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(780, 50, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.comboBox_5 = QtWidgets.QComboBox(self.tab)
        self.comboBox_5.setGeometry(QtCore.QRect(870, 50, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.comboBox_5.setFont(font)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_6 = QtWidgets.QComboBox(self.tab)
        self.comboBox_6.setGeometry(QtCore.QRect(870, 100, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.comboBox_6.setFont(font)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(680, 100, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(10, 100, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_6.setGeometry(QtCore.QRect(210, 100, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.comboBox_7 = QtWidgets.QComboBox(self.tab)
        self.comboBox_7.setGeometry(QtCore.QRect(320, 200, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.comboBox_7.setFont(font)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(220, 200, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setGeometry(QtCore.QRect(380, 200, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_10.setGeometry(QtCore.QRect(440, 200, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_10.setDragEnabled(False)
        self.lineEdit_10.setReadOnly(False)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_18 = QtWidgets.QLabel(self.tab)
        self.label_18.setGeometry(QtCore.QRect(510, 100, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.comboBox_8 = QtWidgets.QComboBox(self.tab)
        self.comboBox_8.setGeometry(QtCore.QRect(600, 100, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.comboBox_8.setFont(font)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.progressBar = QtWidgets.QProgressBar(self.tab)
        self.progressBar.setGeometry(QtCore.QRect(560, 250, 241, 31))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label_21 = QtWidgets.QLabel(self.tab)
        self.label_21.setGeometry(QtCore.QRect(10, 200, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.comboBox_12 = QtWidgets.QComboBox(self.tab)
        self.comboBox_12.setGeometry(QtCore.QRect(60, 200, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.comboBox_12.setFont(font)
        self.comboBox_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.pushButton_16 = QtWidgets.QPushButton(self.tab)
        self.pushButton_16.setGeometry(QtCore.QRect(10, 10, 111, 31))
        self.pushButton_16.setObjectName("pushButton_16")
        self.label_30 = QtWidgets.QLabel(self.tab)
        self.label_30.setGeometry(QtCore.QRect(410, 250, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.tab)
        self.label_31.setGeometry(QtCore.QRect(10, 250, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.progressBar_2 = QtWidgets.QProgressBar(self.tab)
        self.progressBar_2.setGeometry(QtCore.QRect(150, 250, 231, 31))
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setObjectName("progressBar_2")
        self.pushButton_13 = QtWidgets.QPushButton(self.tab)
        self.pushButton_13.setGeometry(QtCore.QRect(140, 10, 121, 31))
        self.pushButton_13.setObjectName("pushButton_13")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_11.setGeometry(QtCore.QRect(130, 10, 681, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_4.setGeometry(QtCore.QRect(840, 10, 71, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_3)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 50, 941, 281))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_35 = QtWidgets.QLabel(self.tab_4)
        self.label_35.setGeometry(QtCore.QRect(10, 110, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.label_34 = QtWidgets.QLabel(self.tab_4)
        self.label_34.setGeometry(QtCore.QRect(180, 60, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.checkBox_5 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_5.setGeometry(QtCore.QRect(290, 20, 201, 16))
        self.checkBox_5.setObjectName("checkBox_5")
        self.pushButton_17 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_17.setGeometry(QtCore.QRect(810, 200, 111, 41))
        self.pushButton_17.setObjectName("pushButton_17")
        self.checkBox_4 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_4.setGeometry(QtCore.QRect(10, 20, 231, 16))
        self.checkBox_4.setObjectName("checkBox_4")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_18.setGeometry(QtCore.QRect(90, 60, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_18.setFont(font)
        self.lineEdit_18.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_18.setDragEnabled(False)
        self.lineEdit_18.setReadOnly(False)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.label_33 = QtWidgets.QLabel(self.tab_4)
        self.label_33.setGeometry(QtCore.QRect(10, 60, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.comboBox_17 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_17.setGeometry(QtCore.QRect(220, 110, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.comboBox_17.setFont(font)
        self.comboBox_17.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_17.setObjectName("comboBox_17")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_21 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_21.setGeometry(QtCore.QRect(540, 110, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.comboBox_21.setFont(font)
        self.comboBox_21.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_21.setObjectName("comboBox_21")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.label_43 = QtWidgets.QLabel(self.tab_4)
        self.label_43.setGeometry(QtCore.QRect(340, 110, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_12.setGeometry(QtCore.QRect(100, 50, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_12.setFont(font)
        self.lineEdit_12.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_12.setDragEnabled(False)
        self.lineEdit_12.setReadOnly(False)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_4 = QtWidgets.QLabel(self.tab_6)
        self.label_4.setGeometry(QtCore.QRect(20, 50, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab_6)
        self.label_5.setGeometry(QtCore.QRect(190, 50, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_5.setGeometry(QtCore.QRect(800, 200, 111, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_28 = QtWidgets.QLabel(self.tab_6)
        self.label_28.setGeometry(QtCore.QRect(20, 100, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.comboBox_13 = QtWidgets.QComboBox(self.tab_6)
        self.comboBox_13.setGeometry(QtCore.QRect(130, 100, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.comboBox_13.setFont(font)
        self.comboBox_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_14 = QtWidgets.QComboBox(self.tab_6)
        self.comboBox_14.setGeometry(QtCore.QRect(470, 100, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.comboBox_14.setFont(font)
        self.comboBox_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.label_29 = QtWidgets.QLabel(self.tab_6)
        self.label_29.setGeometry(QtCore.QRect(360, 100, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.checkBox_3 = QtWidgets.QCheckBox(self.tab_6)
        self.checkBox_3.setGeometry(QtCore.QRect(420, 20, 201, 16))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab_6)
        self.checkBox_2.setGeometry(QtCore.QRect(190, 20, 201, 16))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox = QtWidgets.QCheckBox(self.tab_6)
        self.checkBox.setGeometry(QtCore.QRect(20, 20, 171, 16))
        self.checkBox.setObjectName("checkBox")
        self.comboBox_15 = QtWidgets.QComboBox(self.tab_6)
        self.comboBox_15.setGeometry(QtCore.QRect(320, 50, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.comboBox_15.setFont(font)
        self.comboBox_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_15.setObjectName("comboBox_15")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_16 = QtWidgets.QComboBox(self.tab_6)
        self.comboBox_16.setGeometry(QtCore.QRect(840, 50, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.comboBox_16.setFont(font)
        self.comboBox_16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_16.setObjectName("comboBox_16")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.label_32 = QtWidgets.QLabel(self.tab_6)
        self.label_32.setGeometry(QtCore.QRect(600, 50, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.comboBox_22 = QtWidgets.QComboBox(self.tab_6)
        self.comboBox_22.setGeometry(QtCore.QRect(140, 150, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.comboBox_22.setFont(font)
        self.comboBox_22.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_22.setObjectName("comboBox_22")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.label_39 = QtWidgets.QLabel(self.tab_6)
        self.label_39.setGeometry(QtCore.QRect(20, 150, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_8.setGeometry(QtCore.QRect(800, 210, 111, 41))
        self.pushButton_8.setObjectName("pushButton_8")
        self.checkBox_6 = QtWidgets.QCheckBox(self.tab_7)
        self.checkBox_6.setGeometry(QtCore.QRect(10, 10, 141, 16))
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(self.tab_7)
        self.checkBox_7.setGeometry(QtCore.QRect(160, 10, 201, 16))
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.tab_7)
        self.checkBox_8.setGeometry(QtCore.QRect(380, 10, 201, 16))
        self.checkBox_8.setObjectName("checkBox_8")
        self.comboBox_18 = QtWidgets.QComboBox(self.tab_7)
        self.comboBox_18.setGeometry(QtCore.QRect(730, 50, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.comboBox_18.setFont(font)
        self.comboBox_18.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_18.setObjectName("comboBox_18")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_19 = QtWidgets.QComboBox(self.tab_7)
        self.comboBox_19.setGeometry(QtCore.QRect(730, 110, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.comboBox_19.setFont(font)
        self.comboBox_19.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_19.setObjectName("comboBox_19")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.label_36 = QtWidgets.QLabel(self.tab_7)
        self.label_36.setGeometry(QtCore.QRect(700, 80, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.tab_7)
        self.label_37.setGeometry(QtCore.QRect(700, 20, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.comboBox_20 = QtWidgets.QComboBox(self.tab_7)
        self.comboBox_20.setGeometry(QtCore.QRect(620, 170, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.comboBox_20.setFont(font)
        self.comboBox_20.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_20.setObjectName("comboBox_20")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.label_38 = QtWidgets.QLabel(self.tab_7)
        self.label_38.setGeometry(QtCore.QRect(400, 170, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.comboBox_24 = QtWidgets.QComboBox(self.tab_7)
        self.comboBox_24.setGeometry(QtCore.QRect(120, 170, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.comboBox_24.setFont(font)
        self.comboBox_24.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_24.setObjectName("comboBox_24")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.label_41 = QtWidgets.QLabel(self.tab_7)
        self.label_41.setGeometry(QtCore.QRect(10, 170, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.listWidget_2 = QtWidgets.QListWidget(self.tab_7)
        self.listWidget_2.setGeometry(QtCore.QRect(430, 30, 256, 121))
        self.listWidget_2.setObjectName("listWidget_2")
        self.listWidget = QtWidgets.QListWidget(self.tab_7)
        self.listWidget.setGeometry(QtCore.QRect(100, 30, 256, 121))
        self.listWidget.setObjectName("listWidget")
        self.label_6 = QtWidgets.QLabel(self.tab_7)
        self.label_6.setGeometry(QtCore.QRect(10, 30, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_7.setGeometry(QtCore.QRect(370, 100, 41, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_6.setGeometry(QtCore.QRect(370, 60, 41, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_42 = QtWidgets.QLabel(self.tab_7)
        self.label_42.setGeometry(QtCore.QRect(700, 140, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.comboBox_23 = QtWidgets.QComboBox(self.tab_7)
        self.comboBox_23.setGeometry(QtCore.QRect(730, 170, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.comboBox_23.setFont(font)
        self.comboBox_23.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_23.setObjectName("comboBox_23")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.tabWidget_2.addTab(self.tab_7, "")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_13.setGeometry(QtCore.QRect(600, 10, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_13.setFont(font)
        self.lineEdit_13.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_9.setGeometry(QtCore.QRect(510, 10, 81, 31))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_10.setGeometry(QtCore.QRect(340, 190, 41, 23))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_11.setGeometry(QtCore.QRect(340, 150, 41, 23))
        self.pushButton_11.setObjectName("pushButton_11")
        self.listWidget_3 = QtWidgets.QListWidget(self.tab_2)
        self.listWidget_3.setGeometry(QtCore.QRect(90, 110, 241, 131))
        self.listWidget_3.setObjectName("listWidget_3")
        self.listWidget_4 = QtWidgets.QListWidget(self.tab_2)
        self.listWidget_4.setGeometry(QtCore.QRect(390, 110, 231, 131))
        self.listWidget_4.setObjectName("listWidget_4")
        self.comboBox_10 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_10.setGeometry(QtCore.QRect(870, 210, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.comboBox_10.setFont(font)
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_11 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_11.setGeometry(QtCore.QRect(870, 110, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.comboBox_11.setFont(font)
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.label_23 = QtWidgets.QLabel(self.tab_2)
        self.label_23.setGeometry(QtCore.QRect(670, 110, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.tab_2)
        self.label_24.setGeometry(QtCore.QRect(780, 210, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_12.setGeometry(QtCore.QRect(810, 270, 111, 41))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_14 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_14.setGeometry(QtCore.QRect(690, 270, 111, 41))
        self.pushButton_14.setObjectName("pushButton_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_15.setGeometry(QtCore.QRect(830, 60, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_15.setFont(font)
        self.lineEdit_15.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_15.setDragEnabled(False)
        self.lineEdit_15.setReadOnly(False)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.label_25 = QtWidgets.QLabel(self.tab_2)
        self.label_25.setGeometry(QtCore.QRect(10, 60, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_17.setGeometry(QtCore.QRect(240, 60, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_17.setFont(font)
        self.lineEdit_17.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_17.setDragEnabled(False)
        self.lineEdit_17.setReadOnly(False)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.label_27 = QtWidgets.QLabel(self.tab_2)
        self.label_27.setGeometry(QtCore.QRect(650, 60, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_26 = QtWidgets.QLabel(self.tab_2)
        self.label_26.setGeometry(QtCore.QRect(360, 60, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_16.setGeometry(QtCore.QRect(520, 60, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_16.setFont(font)
        self.lineEdit_16.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_16.setDragEnabled(False)
        self.lineEdit_16.setReadOnly(False)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.pushButton_15 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_15.setGeometry(QtCore.QRect(10, 110, 75, 31))
        self.pushButton_15.setObjectName("pushButton_15")
        self.comboBox_25 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_25.setGeometry(QtCore.QRect(800, 160, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.comboBox_25.setFont(font)
        self.comboBox_25.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_25.setObjectName("comboBox_25")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.label_40 = QtWidgets.QLabel(self.tab_2)
        self.label_40.setGeometry(QtCore.QRect(750, 160, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_14.setGeometry(QtCore.QRect(260, 10, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_14.setFont(font)
        self.lineEdit_14.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.pushButton_18 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_18.setGeometry(QtCore.QRect(130, 10, 121, 31))
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_19.setGeometry(QtCore.QRect(10, 10, 111, 31))
        self.pushButton_19.setObjectName("pushButton_19")
        self.tabWidget.addTab(self.tab_2, "")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 370, 941, 181))
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 975, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PM2RA@XYL_Lab"))
        self.tab.setAccessibleName(_translate("MainWindow", "PM analysis"))
        self.pushButton_3.setText(_translate("MainWindow", "Data file:"))
        self.lineEdit_3.setText(_translate("MainWindow", "D:\\data\\abundance_to_be_analyzed.csv"))
        self.lineEdit_2.setText(_translate("MainWindow", "D:\\data"))
        self.label_8.setText(_translate("MainWindow", "Column name of group indicator:"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "99%"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "95%"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "90%"))
        self.label_9.setText(_translate("MainWindow", "Confidence Interval:"))
        self.label_12.setText(_translate("MainWindow", "Minimum taxa median abundance in control group:"))
        self.lineEdit_9.setText(_translate("MainWindow", "0"))
        self.lineEdit_4.setText(_translate("MainWindow", "5"))
        self.label_7.setText(_translate("MainWindow", "Minimum taxa detection samples in each group:"))
        self.lineEdit_5.setText(_translate("MainWindow", "condition"))
        self.pushButton.setText(_translate("MainWindow", "RESET"))
        self.lineEdit_8.setText(_translate("MainWindow", "control"))
        self.label_11.setText(_translate("MainWindow", "Label of treatment group:"))
        self.pushButton_2.setText(_translate("MainWindow", "RUN"))
        self.lineEdit_7.setText(_translate("MainWindow", "treat"))
        self.label_10.setText(_translate("MainWindow", "Label of control group:"))
        self.label_13.setText(_translate("MainWindow", "ilr transform:"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "ON"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "OFF"))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "ON"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "OFF"))
        self.label_14.setText(_translate("MainWindow", "Automated Best Bandwidth:"))
        self.label_15.setText(_translate("MainWindow", "Minimum coexist taxa number:"))
        self.lineEdit_6.setText(_translate("MainWindow", "5"))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "ON"))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "OFF"))
        self.label_16.setText(_translate("MainWindow", "Multi threading:"))
        self.label_17.setText(_translate("MainWindow", "Threads:"))
        self.lineEdit_10.setText(_translate("MainWindow", "4"))
        self.label_18.setText(_translate("MainWindow", "FDR adjust:"))
        self.comboBox_8.setItemText(0, _translate("MainWindow", "ON"))
        self.comboBox_8.setItemText(1, _translate("MainWindow", "OFF"))
        self.label_21.setText(_translate("MainWindow", "Kernel:"))
        self.comboBox_12.setItemText(0, _translate("MainWindow", "gaussian"))
        self.comboBox_12.setItemText(1, _translate("MainWindow", "epanechnikov"))
        self.pushButton_16.setText(_translate("MainWindow", "Load project"))
        self.label_30.setText(_translate("MainWindow", "2D analysis progress:"))
        self.label_31.setText(_translate("MainWindow", "1D analysis progress:"))
        self.pushButton_13.setText(_translate("MainWindow", "Project storage:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "PM network analysis"))
        self.lineEdit_11.setText(_translate("MainWindow", "D:\\project\\demoproject\\project.pm"))
        self.label_3.setText(_translate("MainWindow", "Project file:"))
        self.pushButton_4.setText(_translate("MainWindow", "Browser"))
        self.label_35.setText(_translate("MainWindow", "Filter statistical significant taxa:"))
        self.label_34.setText(_translate("MainWindow", "taxa with highest PM scores."))
        self.checkBox_5.setText(_translate("MainWindow", "Plot the T-squared statistics"))
        self.pushButton_17.setText(_translate("MainWindow", "Plot"))
        self.checkBox_4.setText(_translate("MainWindow", "Plot the taxa abundance chart"))
        self.lineEdit_18.setText(_translate("MainWindow", "10"))
        self.label_33.setText(_translate("MainWindow", "Plot the top "))
        self.comboBox_17.setItemText(0, _translate("MainWindow", "ON"))
        self.comboBox_17.setItemText(1, _translate("MainWindow", "OFF"))
        self.comboBox_21.setItemText(0, _translate("MainWindow", "Density Chart"))
        self.comboBox_21.setItemText(1, _translate("MainWindow", "Box Chart"))
        self.comboBox_21.setItemText(2, _translate("MainWindow", "Violin Chart"))
        self.label_43.setText(_translate("MainWindow", "Taxa abundance chart type："))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Plot 1D PM taxa difference"))
        self.lineEdit_12.setText(_translate("MainWindow", "30"))
        self.label_4.setText(_translate("MainWindow", "Plot the top "))
        self.label_5.setText(_translate("MainWindow", "edges with highest"))
        self.pushButton_5.setText(_translate("MainWindow", "Plot"))
        self.label_28.setText(_translate("MainWindow", "Edge color map:"))
        self.comboBox_13.setItemText(0, _translate("MainWindow", "Greys"))
        self.comboBox_13.setItemText(1, _translate("MainWindow", "Purples"))
        self.comboBox_13.setItemText(2, _translate("MainWindow", "Blues"))
        self.comboBox_13.setItemText(3, _translate("MainWindow", "Greens"))
        self.comboBox_13.setItemText(4, _translate("MainWindow", "Oranges"))
        self.comboBox_13.setItemText(5, _translate("MainWindow", "Reds"))
        self.comboBox_13.setItemText(6, _translate("MainWindow", "Yellow-orange-brown"))
        self.comboBox_13.setItemText(7, _translate("MainWindow", "Yellow-orange-red"))
        self.comboBox_13.setItemText(8, _translate("MainWindow", "Orange-red"))
        self.comboBox_13.setItemText(9, _translate("MainWindow", "Purple-red"))
        self.comboBox_13.setItemText(10, _translate("MainWindow", "Red-purple"))
        self.comboBox_13.setItemText(11, _translate("MainWindow", "Blue-purple"))
        self.comboBox_13.setItemText(12, _translate("MainWindow", "Green-blue"))
        self.comboBox_13.setItemText(13, _translate("MainWindow", "Purple-blue"))
        self.comboBox_13.setItemText(14, _translate("MainWindow", "Yellow-green-blue"))
        self.comboBox_13.setItemText(15, _translate("MainWindow", "Purple-blue-green"))
        self.comboBox_13.setItemText(16, _translate("MainWindow", "Blue-green"))
        self.comboBox_13.setItemText(17, _translate("MainWindow", "Yellow-green"))
        self.comboBox_14.setItemText(0, _translate("MainWindow", "Greys"))
        self.comboBox_14.setItemText(1, _translate("MainWindow", "Purples"))
        self.comboBox_14.setItemText(2, _translate("MainWindow", "Blues"))
        self.comboBox_14.setItemText(3, _translate("MainWindow", "Greens"))
        self.comboBox_14.setItemText(4, _translate("MainWindow", "Oranges"))
        self.comboBox_14.setItemText(5, _translate("MainWindow", "Reds"))
        self.comboBox_14.setItemText(6, _translate("MainWindow", "Yellow-orange-brown"))
        self.comboBox_14.setItemText(7, _translate("MainWindow", "Yellow-orange-red"))
        self.comboBox_14.setItemText(8, _translate("MainWindow", "Orange-red"))
        self.comboBox_14.setItemText(9, _translate("MainWindow", "Purple-red"))
        self.comboBox_14.setItemText(10, _translate("MainWindow", "Red-purple"))
        self.comboBox_14.setItemText(11, _translate("MainWindow", "Blue-purple"))
        self.comboBox_14.setItemText(12, _translate("MainWindow", "Green-blue"))
        self.comboBox_14.setItemText(13, _translate("MainWindow", "Purple-blue"))
        self.comboBox_14.setItemText(14, _translate("MainWindow", "Yellow-green-blue"))
        self.comboBox_14.setItemText(15, _translate("MainWindow", "Purple-blue-green"))
        self.comboBox_14.setItemText(16, _translate("MainWindow", "Blue-green"))
        self.comboBox_14.setItemText(17, _translate("MainWindow", "Yellow-green"))
        self.label_29.setText(_translate("MainWindow", "Node color map:"))
        self.checkBox_3.setText(_translate("MainWindow", "Plot the T-squared statistics"))
        self.checkBox_2.setText(_translate("MainWindow", "Plot the taxa abundance chart"))
        self.checkBox.setText(_translate("MainWindow", "Plot the PM network"))
        self.comboBox_15.setItemText(0, _translate("MainWindow", "2D PM Scores"))
        self.comboBox_15.setItemText(1, _translate("MainWindow", "Interaction PM scores"))
        self.comboBox_16.setItemText(0, _translate("MainWindow", "ON"))
        self.comboBox_16.setItemText(1, _translate("MainWindow", "OFF"))
        self.label_32.setText(_translate("MainWindow", "Filter statistical significant edges:"))
        self.comboBox_22.setItemText(0, _translate("MainWindow", "Spring Layout"))
        self.comboBox_22.setItemText(1, _translate("MainWindow", "Fruchterman Reingold Layout"))
        self.comboBox_22.setItemText(2, _translate("MainWindow", "Shell Layout"))
        self.comboBox_22.setItemText(3, _translate("MainWindow", "Spectral Layout"))
        self.comboBox_22.setItemText(4, _translate("MainWindow", "Kamada Kawai Layout"))
        self.comboBox_22.setItemText(5, _translate("MainWindow", "Circular Layout"))
        self.label_39.setText(_translate("MainWindow", "Network Layout："))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "Plot PM network with top PM scores"))
        self.pushButton_8.setText(_translate("MainWindow", "Plot"))
        self.checkBox_6.setText(_translate("MainWindow", "Plot the PM network"))
        self.checkBox_7.setText(_translate("MainWindow", "Plot the taxa abundance chart"))
        self.checkBox_8.setText(_translate("MainWindow", "Plot the T-squared statistics"))
        self.comboBox_18.setItemText(0, _translate("MainWindow", "Greys"))
        self.comboBox_18.setItemText(1, _translate("MainWindow", "Purples"))
        self.comboBox_18.setItemText(2, _translate("MainWindow", "Blues"))
        self.comboBox_18.setItemText(3, _translate("MainWindow", "Greens"))
        self.comboBox_18.setItemText(4, _translate("MainWindow", "Oranges"))
        self.comboBox_18.setItemText(5, _translate("MainWindow", "Reds"))
        self.comboBox_18.setItemText(6, _translate("MainWindow", "Yellow-orange-brown"))
        self.comboBox_18.setItemText(7, _translate("MainWindow", "Yellow-orange-red"))
        self.comboBox_18.setItemText(8, _translate("MainWindow", "Orange-red"))
        self.comboBox_18.setItemText(9, _translate("MainWindow", "Purple-red"))
        self.comboBox_18.setItemText(10, _translate("MainWindow", "Red-purple"))
        self.comboBox_18.setItemText(11, _translate("MainWindow", "Blue-purple"))
        self.comboBox_18.setItemText(12, _translate("MainWindow", "Green-blue"))
        self.comboBox_18.setItemText(13, _translate("MainWindow", "Purple-blue"))
        self.comboBox_18.setItemText(14, _translate("MainWindow", "Yellow-green-blue"))
        self.comboBox_18.setItemText(15, _translate("MainWindow", "Purple-blue-green"))
        self.comboBox_18.setItemText(16, _translate("MainWindow", "Blue-green"))
        self.comboBox_18.setItemText(17, _translate("MainWindow", "Yellow-green"))
        self.comboBox_19.setItemText(0, _translate("MainWindow", "Greys"))
        self.comboBox_19.setItemText(1, _translate("MainWindow", "Purples"))
        self.comboBox_19.setItemText(2, _translate("MainWindow", "Blues"))
        self.comboBox_19.setItemText(3, _translate("MainWindow", "Greens"))
        self.comboBox_19.setItemText(4, _translate("MainWindow", "Oranges"))
        self.comboBox_19.setItemText(5, _translate("MainWindow", "Reds"))
        self.comboBox_19.setItemText(6, _translate("MainWindow", "Yellow-orange-brown"))
        self.comboBox_19.setItemText(7, _translate("MainWindow", "Yellow-orange-red"))
        self.comboBox_19.setItemText(8, _translate("MainWindow", "Orange-red"))
        self.comboBox_19.setItemText(9, _translate("MainWindow", "Purple-red"))
        self.comboBox_19.setItemText(10, _translate("MainWindow", "Red-purple"))
        self.comboBox_19.setItemText(11, _translate("MainWindow", "Blue-purple"))
        self.comboBox_19.setItemText(12, _translate("MainWindow", "Green-blue"))
        self.comboBox_19.setItemText(13, _translate("MainWindow", "Purple-blue"))
        self.comboBox_19.setItemText(14, _translate("MainWindow", "Yellow-green-blue"))
        self.comboBox_19.setItemText(15, _translate("MainWindow", "Purple-blue-green"))
        self.comboBox_19.setItemText(16, _translate("MainWindow", "Blue-green"))
        self.comboBox_19.setItemText(17, _translate("MainWindow", "Yellow-green"))
        self.label_36.setText(_translate("MainWindow", "Node color map:"))
        self.label_37.setText(_translate("MainWindow", "Edge color map:"))
        self.comboBox_20.setItemText(0, _translate("MainWindow", "ON"))
        self.comboBox_20.setItemText(1, _translate("MainWindow", "OFF"))
        self.label_38.setText(_translate("MainWindow", "Filter statistical significant edges:"))
        self.comboBox_24.setItemText(0, _translate("MainWindow", "Spring Layout"))
        self.comboBox_24.setItemText(1, _translate("MainWindow", "Fruchterman Reingold Layout"))
        self.comboBox_24.setItemText(2, _translate("MainWindow", "Shell Layout"))
        self.comboBox_24.setItemText(3, _translate("MainWindow", "Spectral Layout"))
        self.comboBox_24.setItemText(4, _translate("MainWindow", "Kamada Kawai Layout"))
        self.comboBox_24.setItemText(5, _translate("MainWindow", "Circular Layout"))
        self.label_41.setText(_translate("MainWindow", "Network Layout："))
        self.label_6.setText(_translate("MainWindow", "Select taxa:"))
        self.pushButton_7.setText(_translate("MainWindow", "<--"))
        self.pushButton_6.setText(_translate("MainWindow", "-->"))
        self.label_42.setText(_translate("MainWindow", "PM score type："))
        self.comboBox_23.setItemText(0, _translate("MainWindow", "2D PM Scores"))
        self.comboBox_23.setItemText(1, _translate("MainWindow", "Interaction PM scores"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("MainWindow", "Plot PM network within ceratin taxas"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "PM network charts"))
        self.lineEdit_13.setText(_translate("MainWindow", "D:\\data\\abundance_to_be_analyzed.csv"))
        self.pushButton_9.setText(_translate("MainWindow", "Data file:"))
        self.pushButton_10.setText(_translate("MainWindow", "<--"))
        self.pushButton_11.setText(_translate("MainWindow", "-->"))
        self.comboBox_10.setItemText(0, _translate("MainWindow", "ON"))
        self.comboBox_10.setItemText(1, _translate("MainWindow", "OFF"))
        self.comboBox_11.setItemText(0, _translate("MainWindow", "ON"))
        self.comboBox_11.setItemText(1, _translate("MainWindow", "OFF"))
        self.label_23.setText(_translate("MainWindow", "Wether Find Best Bandwidth:"))
        self.label_24.setText(_translate("MainWindow", "ilr transform:"))
        self.pushButton_12.setText(_translate("MainWindow", "RUN"))
        self.pushButton_14.setText(_translate("MainWindow", "RESET"))
        self.lineEdit_15.setText(_translate("MainWindow", "treat"))
        self.label_25.setText(_translate("MainWindow", "Column name of group indicator:"))
        self.lineEdit_17.setText(_translate("MainWindow", "condition"))
        self.label_27.setText(_translate("MainWindow", "Label of treatment group:"))
        self.label_26.setText(_translate("MainWindow", "Label of control group:"))
        self.lineEdit_16.setText(_translate("MainWindow", "control"))
        self.pushButton_15.setText(_translate("MainWindow", "Select taxa"))
        self.comboBox_25.setItemText(0, _translate("MainWindow", "gaussian"))
        self.comboBox_25.setItemText(1, _translate("MainWindow", "epanechnikov"))
        self.label_40.setText(_translate("MainWindow", "Kernel:"))
        self.lineEdit_14.setText(_translate("MainWindow", "D:\\data"))
        self.pushButton_18.setText(_translate("MainWindow", "Project storage:"))
        self.pushButton_19.setText(_translate("MainWindow", "Load project"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Module analysis"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Logs...</p></body></html>"))
        self.menu.setTitle(_translate("MainWindow", "Menu"))
